title: 赵都建设
company: 北京赵都建设工程有限公司
tel: 
address: 
com_detail: <p>北京赵都建设工程有限公司是建设部批准多项专业工程资质企业，具备贰级资质五项，叁级资质八项、施工专业不分等级一项，总一十四项资质。</p><p>企业成长之初便与各大建筑企业集团精诚合作、共同发展，在全国共同建设多个大型项目，取得了显著的成绩。公司以强化质量意识，严格过程管理，提供优质工程，赢得多家国有建筑企业及上市公司信赖，建立长期战略合作关系。</p><p>公司以人为本，科学管理的方针下，内设质量管理体系、安全生产管理体系、财务管理体系及服务管理体系。</P><p>目前公司从业人员已达2000余人，拥有各类技术管理人员200余人，其中：专业技术人员50余人，项目经理20人，中级工程师职称6人，一级建造师5人，二级建造师15人，其他管理人员100余人。</p><p>我公司坚持“信誉为本、服务是根、注重细节、追求完美”的经营理念不断加强服务及内部管理，注重提高自身素质，始终坚持信誉至上，质量第一，安全生产，文明施工的原则，树立了良好的社会形象，赢得了较好的经济效益和社会信誉。公司现今全面推行质量管理，已达到ISO9001质量管理标准。</p><p>公司在抓生产经营和施工管理的同时，注重精神文明建设，大力弘扬“共同发展、开拓创新”的行业精神，坚持以人为本的核心价值观，建立了并完善了人才资源库，让所有员能够在自己的岗位上充分发挥特长，公司上下形成了团结、实干、求发展的良好企业文化氛围。</p><p>本公司将充分发挥自身的管理优势、人才优势，结合社会发展需求，不断探讨企业的优化组合框架，贯彻ISO9001标准和《建筑工程质量管理条例》，接受用户监督，竭诚为社会各界提供优质的建筑产品和良好的服务，与社会各界共创美好未来。</p>
collections:
 anlis: 
   name: 经典案例
   output: true
 about:
   name: 关于我们
   output: true
 falv:
   name: 法律法规
   output: true
 fuwu:
   name: 服务领域
   output: true
 
detach:  true
#port:    4000
#host:    192.168.88.101
baseurl: "" # does not include hostname
